apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-rest-customer
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-rest-customer
  template:
    metadata:
      labels:
        app: service-rest-customer
    spec:
      containers:
        - name: service-rest-customer
          image: cp22590/service-rest-customer:1.0.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:oracle:thin:aqdb/aqdb@//10.5.0.2:1521/orclpdb
            - name: SPRING_DATASOURCE_USERNAME
              value: aqdb
            - name: SPRING_DATASOURCE_PASSWORD
              value: tiger
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: http://elasticsearch.efk.svc.cluster.local:9200
          volumeMounts:
            - name: app-logs
              mountPath: /logs
        - name: fluent-bit
          image: fluent/fluent-bit:1.6
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          volumeMounts:
            - name: app-logs
              mountPath: /logs
            - name: config-volume
              mountPath: /fluent-bit/etc
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: customer-fluent-bit-config